package com.lambdaschool.zoos.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;


/**
 * The entity allowing interaction with the zoos table
 */
@Entity
@Table(name = "zoos")
public class Zoo extends Auditable {

    /**
     * The primary key (long) of the zoos table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long zooid;

    /**
     * The zoo name (String). Cannot be null and must be unique
     */
    @Column(nullable = false,
            unique = true)
    private String zooname;

    /**
     * List of telephone numbers associated with this zoo. Does not get saved in the database directly.
     * Forms a one to many relationship with telephones. One zoo to many telephones.
     */
    @OneToMany(mappedBy = "zoo",
            cascade = CascadeType.ALL,
            orphanRemoval = true)
    @JsonIgnoreProperties(value = "zoo")
    private List<Telephone> telephones = new ArrayList<>();

    /**
     * Creates a join table (zooanimals) joining Zoos and Animals vai two One-To-Many relations.
     *
     */
    @OneToMany(mappedBy = "zoo", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnoreProperties(value = "zoo")
    private Set<ZooAnimals> animals = new HashSet<>();

    /**
     * Default constructor used primarily by the JPA.
     */
    public Zoo() {
    }

    /**
     * Given the params, create a new user object
     *
     * zooid is autogenerated
     *
     * @param zooname     The name (String) of the zoo
     */
    public Zoo(long zooid, String zooname) {
        this.zooid = zooid;
        this.zooname = zooname;
    }

    /**
     * Getter for zooid
     *
     * @return the zooid (long) of the zoo
     */
    public long getZooid() {
        return zooid;
    }

    /**
     * Setter for zooid. Used primarily for seeding data
     *
     * @param zooid the new zooid (long) of the zoo
     */
    public void setZooid(long zooid) {
        this.zooid = zooid;
    }

    /**
     * Getter for zooname
     *
     * @return the zooname (String) of the zoo
     */
    public String getZooname() {
        return zooname;
    }

    /**
     * Setter for zooname. Used primarily for seeding data
     *
     * @param zooname the new zooname (String) of the zoo
     */
    public void setZooname(String zooname) {
        this.zooname = zooname;
    }

    public List<Telephone> getTelephones() {
        return telephones;
    }

    public void setTelephones(List<Telephone> telephones) {
        this.telephones = telephones;
    }

    public Set<ZooAnimals> getAnimals() {
        return animals;
    }

    public void setAnimals(Set<ZooAnimals> animals) {
        this.animals = animals;
    }
}